### ISSUE TITLE
Extend pre-commit hooks

### ISSUE THREAD

**Issue by katunilya** [katunilya/pymon#107]
Reference `.pre-commit-config.yaml`

```yml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
        stages: [commit]
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        stages: [commit]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            yastyleguide==0.0.5a
        ]
        stages: [commit, push]

```
